### ISSUE TITLE
テストを網羅的に記述する

### ISSUE THREAD

**Issue by yk-saito** [unchain-tech/ICP-Basic-DEX#17]
- [x]  提出物が学習コンテンツ通りに作成されているかの動作確認ができる、テストスクリプトを追加する
- [x]  https://github.com/shiftbase-inc/UNCHAIN-test-submissions から実行できるようにする

**Comment by yk-saito** [comment]
@neila 
`codebuild`上での動作確認OKです！
- [build run log](https://ap-northeast-1.console.aws.amazon.com/codesuite/codebuild/733910873054/projects/stg-codetest/build/stg-codetest%3A22c2a643-5d9d-4256-86e8-2e37f10d79fc/log?region=ap-northeast-1)

**Comment by neila** [comment]
lgtm b
